### ISSUE TITLE
Errors do not count as test failures

### ISSUE THREAD

**Issue by LeifAndersen** [racket/rackunit#13]
When I run `raco test` on a bunch of tests that use rackunit that fail, the program indicates that tests failed, gives the number of tests that failed, and seems to give a non zero status code indicating to any external scripts that tests failed.

However, if the tests errored rather than failed, none of this happens. The error message is printed to stdout, and when the results are printed it is properly included in the report, but the tests otherwise seem to pass, and give a 0 for the return code.

This seems odd to me that the behavior for tests erroring is closer to that of tests passing, rather than that of tests failing.

Is this expected behavior?

**Comment by jeapostrophe** [comment]
Can you give a short example?

**Comment by LeifAndersen** [comment]
Sure. Here is a file with a failed test, and as expected, rackunit causes the program gives a 1 for its return code:

```
#lang racket

(module+ test
  (require rackunit
           rackunit/text-ui)
  (define a
    (test-suite "Test Suite"
      (test-case "Test Case"
        (check-equal? #t #f))))
  (run-tests a))
```

And here is a similar program, except rather than failing, the tests errors. When you run raco test on this program, and see what the return is with `$?`, it gives a 0 rather than a 1, even though the test errored:

```
#lang racket

(module+ test
  (require rackunit
           rackunit/text-ui)
  (define a
    (test-suite "Test Suite"
      (test-case "Test Case"
        (check-equal? (error "I'm an error!") #f))))
  (run-tests a))
```

**Comment by jeapostrophe** [comment]
This is more complicated than it appears to you. From rackunit's
perspective, no error occurred in the second case, because
`check-equal?` takes two values and you never gave it two values, so
rackunit's `check-equal?` never ran. For instance, if you just write

```
(check-equal? (error "I'm an error!") #f)
```

In your program, you'll see there is no output from `rackunit`,
because `rackunit` never ran.

So, I changed `test-case` so it counts exceptions during the
`test-case` as failures.

In summary, this particular program is now working, but I suspect if
it is part of a bigger program not involving `test-case`, then it
won't work.


On Sat, Dec 19, 2015 at 10:25 PM, Leif Andersen
<notifications@github.com> wrote:
> Sure. Here is a file with a failed test, and as expected, rackunit causes
> the program gives a 1 for its return code:
>
> #lang racket
>
> (module+ test
>   (require rackunit
>            rackunit/text-ui)
>   (define a
>     (test-suite "Test Suite"
>       (test-case "Test Case"
>         (check-equal? #t #f))))
>   (run-tests a))
>
> And here is a similar program, except rather than failing, the tests errors.
> When you run raco test on this program, and see what the return is with $?,
> it gives a 0 rather than a 1, even though the test errored:
>
> #lang racket
>
> (module+ test
>   (require rackunit
>            rackunit/text-ui)
>   (define a
>     (test-suite "Test Suite"
>       (test-case "Test Case"
>         (check-equal? (error "I'm an error!") #f))))
>   (run-tests a))
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by LeifAndersen** [comment]
Oh, interesting. Well thanks for at least fixing the immediate issue. I'll let you know if I see any other odities like this.
