### ISSUE TITLE
Testing a check with a check

### ISSUE THREAD

**Issue by vdloo** [racket/rackunit#14]
Hi,

I'm trying to write a test for a custom check but I can't seem to figure it out. The check under test shows up as a failed test in the `raco test` output. Is there a way to do this? If so, what am I doing wrong?

My check

```
(define-check (check-mock-called-with? args mock)
  (let ([result (mock-called-with? args mock)])
    (with-check-info
      [('expected args) ('actual (mock-calls mock))]
      (unless result
        (fail-check "Actual arguments did not match expected")))))
```

The test for the check

```
  (test-case
    "check-info is added by check-mock-called-with? on failure"
    (check-exn
      (λ (e) (and (has-info? e 'expected) (has-info? e 'actual)))
      (thunk
        (parameterize ([current-check-handler raise])
          (check-mock-called-with? '(1) (void-mock)))))))
```

Running the test yields 1/2 failed tests. The succeeded test is the outer one (which is good) but the inner one shows up as a failure, which it shouldn't because that's part of the test. I expected the inner test to not register in the raco test output because its exception is raised by the current check handler instead of printed.

More info: https://github.com/jackfirth/racket-mock/pull/20

**Comment by bennn** [comment]
I don't there's any way to call `fail-check` and not report a test failure.

Idea 1: change `fail-check`, submit a pull request

**Comment by jackfirth** [comment]
@bennn Idea 2 wouldn't cooperate well with code coverage metrics because there'd be no way to cover the `fail-check` branch of the parameter-based conditional with a passing test. You could maybe isolate the problem to one single wrapper point around `fail-check`, but you can't get 100% coverage.

**Comment by bennn** [comment]
I see. 
http://labs.ig.com/code-coverage-100-percent-tragedy
Maybe try fooling the coverage tool with a syntax parameter? (So there's no `if`, just one line of code which is sometimes a `fail-check` and sometimes something else, depending on expansion-time info)

**Comment by jackfirth** [comment]
If I'm not going to cover something in my test suite, I'd prefer that be because I've decided it's not something worth testing, not because it's *not possible* to test it properly.

If there's going to be a parameter, expansion-time or otherwise, for disabling parts of the behavior of `fail-check` that seems like something that belongs in RackUnit proper alongside some other tools for testing custom checks. I wouldn't want to write and maintain something like that in every project of mine that defines custom checks.

My work-in-progress [expect](https://github.com/jackfirth/racket-expect) library is partially a way to get around this; in that library checks ("expectations") are first class pure functions that are separately hooked into RackUnit and the check-info system. That way checks can be tested like normal functions, custom checks become much simpler to create, and checks become much easier to combine.
