### ISSUE TITLE
rackunit/text-ui duplicates a lot of code in rackunit/private/format

### ISSUE THREAD

**Issue by jackfirth** [racket/rackunit#35]
This makes it tricky to implement things like #10. There's also several "nice to have" things in text-ui that could benefit from a more principled API, for instance:

- `run-tests` treats certain info fields as "verbose" fields, specifically the `expression` field. It might be nice to have a `verbose-info` wrapper struct similar to `string-info` that causes the info to not be printed by default and only printed when `run-tests` is run in verbose mode.
- `run-tests` adjusts the source location value in the `location` field to print as a relative directory path. A `location-info` wrapper struct that let users trigger this behavior for other srcloc fields could be useful.
- `run-tests` uses `pretty-print` on certain values. A `pretty-info` wrapper could work, but `run-tests` is a little weird because it pretty prints values in the `expected` and `actual` fields but it *maps* `pretty-print` over the *list* of values in the `params` field. Maybe that behavior should be changed?

A radical approach to this problem is to pull `rackunit/text-ui` out into its own package. I did this as an experiment on my own fork to see what changes need to be made to `text-ui` to remove its dependency on rackunit's internal error formatting code. If that seems like a useful thing to do, I can open a PR.

**Comment by bennn** [comment]
A few thoughts:

#### Implementing Nested Check Info

At first, I don't see how this issue is making #10 difficult. I figure the TODOs for #10 are:
- add a new "check info field" (sorry I don't know if there's a technical term for this)
- design a datatype for this field, made of strings and structs-to-guide formatting
- implement a printer that interprets the datatype and outputs text like #10 suggests

All three of those could be done just in `rackunit/text-ui` right?

I guess the trouble would be if you wanted to re-use a `rackunit/private/format` function at +1 indentation.

Do you want to open issues or list the other things like #10 that you want?

#### More Principled API

All these `-info` structs sound good. I think it'd be great if `rackunit/text-ui` did all its printing in a uniform way, guided by a datatype.

Earlier I was thinking rackunit could re-use structs from `scribble/base`. I don't think so anymore. Except for `nested` I think the goals in Scribble are too different.
Maybe though, it will make sense to move some formatting functions into `racket/format` or some other, general place.

Mapping `pretty-print` sounds like a mistake


#### New Package

How did the moving go? Hopefully it was easy, and the few functions it needed from `rackunit/private/format` could be made public to clients?

I don't think `rackunit/text-ui` needs to be its own package. I think it should:
-  use a public API for building `check-info` values
- document how it processes `check-info` values
but whether the processing happens internally in `rackunit/text-ui` or `rackunit/private/format` doesn't matter to me.

**Comment by jackfirth** [comment]
This interacts with #10 because the default failure printing logic for checks is defined in terms of `display-test-failure/error` which is defined in terms of the other exports of `format.rkt`, but `run-tests` doesn't use `display-test-failure/error` and instead duplicates it (but with slight differences) by using the other exports of `format.rkt`. It also strings together the various components of `display-test-failure/error` such as `display-delimiter` using the strange ad-hoc monad implementation in `monad.rkt` and `hash-monad.rkt`. I'm not sure if an implementation to #10 might run into issues because of that.

I'd like to move towards implementing `run-tests` entirely in terms of `display-test-failure/error`. To preserve features of `run-tests` such as verbosity and pretty printing, I'll make specialized "info types" (a technical term I just made up for things like `string-info`) that reproduce the behavior, optionally exposing them to all RackUnit users if they're useful enough.

As far as package splitting, it was helpful in learning what `text-ui` depends on in RackUnit. The formatting logic is the main entanglement between the two; a documented `display-test-result` procedure in RackUnit could sever that tie completely. I agree that actually splitting the packages is not necessary, though I might open a PR to put the files for `text-ui` into their own folder to make the separation clearer.

**Comment by jeapostrophe** [comment]
My general opinion is that text-ui and all the test-case/suite stuff in Rackunit is totally useless and everyone just wants to directly call the various checks directly. My opinion is that it is too complicated and not worth fixing, so I made `chk`, but if people want to improve Rackunit, then separating out the useless stuff is a good idea.

**Comment by samth** [comment]
I use the test-case framework pretty extensively in Typed Racket, and I wish it were both simpler and more flexible. Also, Rackunit is the standard for Racket unit testing, and so we should try to converge on it, rather than moving away from it.

I also think that @jackfirth seems to have good ideas here, and should do them!
